version: "3"

services:
  loraserver:
    image: loraserver/loraserver:3
    volumes:
      - ./configuration/loraserver:/etc/loraserver

  appserver:
          # image: mxcdocker/lora-app-server:0.6
    image: loraserver/lora-app-server:3      
    ports:
      - 8080:8080
        #    volumes:
        #- ./:/lora-app-server
            # - ./configuration/lora-app-server:/etc/lora-app-server
        #    entrypoint:
        #- lora-app-server
    tty: true
    #entrypoint:
    # - lora-app-server

  gatewaybridge:
    image: loraserver/lora-gateway-bridge:3
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/lora-gateway-bridge:/etc/lora-gateway-bridge

  geoserver:
    image: loraserver/lora-geo-server:3
    volumes:
      - ./configuration/lora-geo-server:/etc/lora-geo-server

  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    #restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - appserver
        # networks:
        #- app-network

  m2m:
    image: mxcdocker/node-helloworld:0.1
    container_name: m2m
    ports:
     - "4000:4000"

       # certbot:
       #image: certbot/certbot
       #container_name: certbot
       #volumes:
       #- certbot-etc:/etc/letsencrypt
       #- certbot-var:/var/lib/letsencrypt
       #- web-root:/var/www/html
   # depends_on:
   #   - webserver
   # command: certonly --webroot --webroot-path=/var/www/html --email naser@mxc.org --agree-tos --no-eff-email --force-renewal -d m2m.demo.cloud.mxc.org 
   #tty: true

volumes:
  postgresqldata:
  redisdata:
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      device: /home/naser/loraserver-docker/certbot/conf
      o: bind    
  certbot-var:
    driver: local
    driver_opts:
      type: none
      device: /home/naser/loraserver-docker/certbot/lib
      o: bind
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/naser/loraserver-docker/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/naser/loraserver-docker/dhparam/
      o: bind
